version: '3.9'
services:
  blog-database:
    image: mongo
    ports:
      - '27017:27017'
  blog-backend:
    build: backend/
    environment:
      - PORT=3001
      - DATABASE_URL=mongodb://blog-database:27017/blog
    ports:
      - '3001:3001'
    depends_on:
      - blog-database
  blog-frontend:
    build:
      context: .
      args:
        VITE_BACKEND_URL: https://zany-umbrella-g46xrxvq49952xxr-3001.app.github.dev/api/v1
    ports:
      - '3000:80'
    depends_on:
      - blog-backend